import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 10,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
    textAlign: 'center',
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 15,
    flexWrap: 'wrap',
  },
  filterButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E73E01',
    margin: 5,
    backgroundColor: '#FFF8F0',
  },
  filterButtonActive: {
    backgroundColor: '#E73E01',
    borderColor: '#E73E01',
  },
  filterText: {
    fontSize: 14,
    color: '#E73E01',
    fontWeight: '500',
  },
  filterTextActive: {
    color: '#FFF8F0',
    fontWeight: '600',
  },
  ticketContainer: {
    backgroundColor: '#FFF8F0',
    borderRadius: 8,
    padding: 12,
    margin: 5,
    width: '30%',
    height: 180,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: '#E73E01',
  },
  completedTicket: {
    opacity: 0.7,
    borderLeftColor: '#48BB78',
  },
  ticketContent: {
    flex: 1,
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  orderNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#E73E01',
    marginBottom: 6,
  },
  orderDetails: {
    fontSize: 14,
    color: '#8B5A2B',
    marginBottom: 6,
  },
  status: {
    fontSize: 12,
    color: '#8B5A2B',
    fontWeight: '500',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  iconButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: '#F5E6D3',
    margin: 2,
  },
  deleteButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: '#8B5A2B',
    margin: 2,
    borderWidth: 1,
    borderColor: '#E73E01',
  },
  disabledButton: {
    opacity: 0.5,
  },
  icon: {
    color: '#E73E01',
    fontSize: 18,
  },
  deleteIcon: {
    color: '#FFF8F0',
    fontSize: 18,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  modalContent: {
    backgroundColor: '#FFF8F0',
    padding: 20,
    borderRadius: 12,
    width: '85%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: '#E73E01',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#8B5A2B',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalText: {
    fontSize: 15,
    color: '#8B5A2B',
    marginBottom: 10,
  },
  closeButton: {
    backgroundColor: '#E73E01',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 10,
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: '#FFF8F0',
    fontWeight: '600',
  },
  allPrintButton: {
    backgroundColor: '#F5E6D3',
    padding: 10,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#E73E01',
    marginVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  allPrintIcon: {
    color: '#E73E01',
    fontSize: 24,
  },
  emptyText: {
    fontSize: 16,
    color: '#8B5A2B',
    textAlign: 'center',
    padding: 20,
  },
  columnWrapper: {
    justifyContent: 'space-between',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    width: '100%',
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    width: '48%',
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#8B5A2B',
  },
  deleteButtonModal: {
    backgroundColor: '#E73E01',
  },
  printButtonModal: {
    backgroundColor: '#E73E01',
  },
  modalButtonText: {
    color: '#FFF8F0',
    fontSize: 16,
    fontWeight: 'bold',
  },
  printContentContainer: {
    maxHeight: '60%',
    marginVertical: 10,
    padding: 10,
  },
  printTicketItem: {
    marginBottom: 15,
  },
  printText: {
    fontSize: 16,
    color: '#8B5A2B',
    marginBottom: 5,
  },
  separator: {
    height: 1,
    backgroundColor: '#E73E01',
    marginVertical: 10,
  },
  printDate: {
    fontSize: 14,
    color: '#8B5A2B',
    marginVertical: 10,
    textAlign: 'center',
  },
});